Repository toru-studio/COOP, pull requests merged in 2024-01, with the labels that each got.

#3 Initial Project Setup
  .gitattributes
  README.md
  icon.svg
  icon.svg.import
  project.godot
Labels: Structural

#5 Update README.md
  README.md
Labels: Structural

#18 15 create basic map
  Assets/Images/Environment/BasicTileSheet.png
  Assets/Images/Environment/BasicTileSheet.png.import
  Assets/Images/Towers/Projectile.png.import
  Source/Game/Maps/MapTemp.tscn
Labels: map

#26 Update README.md
  README.md
Labels: structural

#39 30 implement baked lighting system
  Assets/Images/UI/caster.png
  Assets/Images/UI/caster.png.import
  Assets/Images/UI/light.png
  Assets/Images/UI/light.png.import
  Assets/Images/UI/spot.png
  Assets/Images/UI/spot.png.import
  Source/Entities/Fox/fox.tscn
  Source/Game/Scenes/fox-test.tscn
Labels: lighting
